version: '3'
services:
  web:
    env_file:
      - db_credentials.env
    build: .
    ports:
     - "5000:5000"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - db_credentials.env
    volumes:
      - ./mysql-dumps:/docker-entrypoint-initdb.d
        
